# Bitbucket Pipelines build script

image: spivoxity/obc-build

pipelines:
  default:
    - step:
        script:
          - autoreconf
          - ./configure
          - make
          - make test
